# Generated by Django 5.0 on 2023-12-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_element_comments_alter_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='unique_id',
            field=models.UUIDField(default='fake-id', unique=True),
            preserve_default=False,
        ),
    ]
