# Generated by Django 5.0 on 2023-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_element_comments_element_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unique_id',
            field=models.TextField(),
        ),
    ]
