# Generated by Django 5.0 on 2024-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parameter_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='guid',
            field=models.TextField(blank=True),
        ),
    ]
