; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
ArchitecturesInstallIn64BitMode=x64
; --- 1. App Information ---
AppName=Project Perseus
AppVersion=1.1.81
AppId={{10908502-7BB8-473D-B858-B31591187295}}
DefaultGroupName=Andrew Butler

; --- 2. Installation Paths ---
DefaultDirName={autopf}\Project Perseus

; --- 3. Installer Output ---
OutputBaseFilename=Install_ProjectPerseus
Compression=lzma
SolidCompression=yes

; --- 4. The IT Requirement ---
PrivilegesRequired=admin 

; --- 5. App Lifecycle Rules ---
; Warns the user if Revit is open and locking the DLLs
CloseApplications=yes
; Prevents the installer from trying to auto-reboot Revit after installing
RestartApplications=no
; Optional: Adds your plugin icon to the Windows Add/Remove Programs list
; UninstallDisplayIcon={app}\2026\reset.png
[Files]
; --- REVIT 2024 ---
; 1. The DLL payload
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2024\ProjectPerseus.dll"; DestDir: "{app}\2024"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2024\WebView2Loader.dll"; DestDir: "{app}\2024"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2024\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}\2024"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2024\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}\2024"; Flags: ignoreversion

; 2. The Manifest pointer
; {commonappdata} automatically resolves to C:\ProgramData
; Source: "E:\mydev\project-perseus\revit_plugin\manifests\ProjectPerseus_2024.addin"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\2024"; Flags: ignoreversion


; --- REVIT 2025 ---
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2025\ProjectPerseus.dll"; DestDir: "{app}\2025"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2025\WebView2Loader.dll"; DestDir: "{app}\2025"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2025\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}\2025"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2025\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}\2025"; Flags: ignoreversion
; Source: "E:\mydev\project-perseus\revit_plugin\manifests\ProjectPerseus_2025.addin"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\2025"; Flags: ignoreversion


; --- REVIT 2026 ---
Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2026\ProjectPerseus.dll"; DestDir: "{app}\2026"; Flags: ignoreversion
Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2026\runtimes\win-x64\native\WebView2Loader.dll"; DestDir: "{app}\2026\runtimes\win-x64\native"; Flags: ignoreversion
Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2026\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}\2026"; Flags: ignoreversion
Source: "E:\mydev\project-perseus\revit_plugin\src\ProjectPerseus\bin\x64\Debug 2026\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}\2026"; Flags: ignoreversion
Source: "E:\mydev\project-perseus\revit_plugin\manifests\ProjectPerseus_2026.addin"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\2026"; Flags: ignoreversion

[Code]
var
  ServerUrlPage: TInputQueryWizardPage;
  FinalServerUrl: String;

// 1. THIS RUNS WHEN THE INSTALLER STARTS
procedure InitializeWizard;
var
  DefaultUrl: String;
begin
  // Create a custom wizard page right after the "Select Destination" page
  ServerUrlPage := CreateInputQueryPage(wpSelectDir,
    'Server Configuration', 
    'Where should Project Perseus connect?',
    'Please specify the Base URL for your Perseus server.');

  // Add the text input box
  ServerUrlPage.Add('Server Base URL:', False);

  // Read the command line parameter (e.g., /SERVERURL="https://sync.cox.com")
  // If the parameter doesn't exist, it falls back to the default URL provided after the pipe (|)
  DefaultUrl := ExpandConstant('{param:SERVERURL|https://perseus.coxarchitecture.com}');

  // Pre-fill the text box with the result
  ServerUrlPage.Values[0] := DefaultUrl;
end;

// 2. THIS RUNS RIGHT AFTER THE FILES ARE COPIED
procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigDir: String;
  ConfigFile: String;
  JsonContent: String;
begin
  // We only want to write the config file at the very end of the installation
  if CurStep = ssPostInstall then
  begin
    // Grab whatever value was in the text box (whether typed manually or injected via CLI)
    FinalServerUrl := ServerUrlPage.Values[0];

    // --- DEFINE WHERE YOUR C# CONFIG FILE LIVES ---
    // {userappdata} resolves to C:\Users\Username\AppData\Roaming
    ConfigDir := ExpandConstant('{userappdata}\Project Perseus');
    ConfigFile := ConfigDir + '\config.json';

    // Create the folder if it doesn't exist yet
    if not DirExists(ConfigDir) then
      CreateDir(ConfigDir);

    // Build the JSON string to match what your C# Config.Instance expects
    // Note: Pascal uses #13#10 for line breaks
    JsonContent := '{' + #13#10 +
                   '  "BaseUrl": "' + FinalServerUrl + '"' + #13#10 +
                   '}';

    // Save the text to the config.json file (False = overwrite, do not append)
    SaveStringToFile(ConfigFile, JsonContent, False);
  end;
end;