# Generated by Django 5.0 on 2025-10-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('element', 'name')},
        ),
    ]
