# Generated by Django 5.0 on 2025-10-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unique_id',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
