# Generated by Django 5.0 on 2025-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('element', 'name'), name='unique_element_parameter_name'),
        ),
    ]
