# Generated by Django 4.2.7 on 2023-11-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
