# Generated by Django 5.0 on 2025-10-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parameter_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parameter',
            name='unique_element_parameter_name',
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('element', 'name')},
        ),
    ]
