# Generated by Django 5.0 on 2023-12-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_element_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='comments',
        ),
        migrations.AddField(
            model_name='element',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
