# Generated by Django 5.0 on 2023-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_element_parameters_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
