# Generated by Django 5.0 on 2024-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='unique_id',
            field=models.TextField(unique=True),
        ),
    ]
