# Generated by Django 5.0 on 2024-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_element_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='guid',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
