# Generated by Django 5.0 on 2024-01-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_parameter_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='guid',
        ),
    ]
