# Generated by Django 5.0 on 2025-10-02 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_parameter_name_alter_parameter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
