# Generated by Django 5.0 on 2025-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_element_created_at_element_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.TextField(),
        ),
    ]
