# Generated by Django 5.0 on 2025-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_parameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_id',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
