# Generated by Django 5.0 on 2025-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_element_element_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
