# Generated by Django 5.0 on 2025-10-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set(),
        ),
    ]
