# Generated by Django 5.0 on 2025-10-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_parameter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='last_edited_by',
            field=models.TextField(blank=True),
        ),
    ]
