# Generated by Django 5.0 on 2025-10-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_element_last_edited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(unique=True)),
                ('name', models.TextField(blank=True)),
                ('medium', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='source_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.source'),
        ),
    ]
