# Generated by Django 5.0 on 2025-10-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_source_element_source_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='source_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
