# Generated by Django 5.0 on 2025-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_element_source_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_id',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='element',
            name='last_edited_by',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='element',
            name='source_state',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='unique_id',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='medium',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='unique_id',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
